## Arithmetic Operations with NumPy

### Finding Square Roots

In [1]:
import numpy as np

nums = [10, 20, 30, 40, 50]
np_sqrt = np.sqrt(nums)
print(np_sqrt)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


### Finding Logs

In [2]:
import numpy as np

nums = [ 10 , 20 , 30 , 40 , 50 ]
np_log = np.log(nums)
print (np_log)

[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


### Finding Exponents

In [3]:
import numpy as np

nums = [ 10 , 20 , 30 , 40 , 50 ]
np_exp = np.exp(nums)
print (np_exp)

[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]


### Finding Sine and Cosine

In [4]:
import numpy as np

nums = [ 10 , 20 , 30 , 40 , 50 ]
np_sine = np.sin(nums)
print (np_sine)

np_cos = np.cos(nums)
print (np_cos)

[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]


## NumPy for Linear Algebra Operations

### Finding the Matrix Dot Product

In [5]:
import numpy as np

A = np.random.randn( 4 , 5 )
B = np.random.randn( 5 , 4 )

Z = np.dot(A,B)
print (Z)

[[-0.19956475  1.01091704  0.65855907  0.50025365]
 [ 2.16339152  0.25911384  0.89935553 -0.11963211]
 [ 1.60300225 -2.17784408 -2.62573155 -0.90811182]
 [-1.23556254  2.21309902  0.16409055  0.92335065]]


### Element-wise Matrix Multiplication

In [6]:
import numpy as np

row1 = [ 10 , 12 , 13 ]
row2 = [ 45 , 32 , 16 ]
row3 = [ 45 , 32 , 16 ]

nums_2d = np.array([row1, row2, row3])
multiply = np.multiply(nums_2d, nums_2d)
print (multiply)

[[ 100  144  169]
 [2025 1024  256]
 [2025 1024  256]]


### Finding the Matrix Inverse

In [7]:
import numpy as np

row1 = [ 1 , 2 , 3 ]
row2 = [ 5 , 2 , 8 ]
row3 = [ 9 , 1 , 10 ]

nums_2d = np.array([row1, row2, row3])
inverse = np.linalg.inv(nums_2d)
print (inverse)

[[ 0.70588235 -1.          0.58823529]
 [ 1.29411765 -1.          0.41176471]
 [-0.76470588  1.         -0.47058824]]


### Finding the Matrix Determinant

In [8]:
import numpy as np

row1 = [ 1 , 2 , 3 ]
row2 = [ 5 , 2 , 8 ]
row3 = [ 9 , 1 , 10 ]

nums_2d = np.array([row1, row2, row3])
determinant = np.linalg.det(nums_2d)
print (determinant)

17.0


### Finding the Matrix Trace

In [9]:
import numpy as np

row1 = [ 1 , 2 , 3 ]
row2 = [ 4 , 5 , 6 ]
row3 = [ 7 , 8 , 9 ]

nums_2d = np.array([row1, row2, row3])
trace = np.trace(nums_2d)
print (trace)

15


### Solving a System of Linear Equations with Python

In [10]:
import numpy as np

A = np.array([[ 6 , 3 ], [ 2 , 4 ]])
B = np.array([ 42 , 32 ])

In [11]:
A_inv = np.linalg.inv(A)
print (A_inv)

[[ 0.22222222 -0.16666667]
 [-0.11111111  0.33333333]]


In [12]:
X = np.dot(A_inv, B)
print (X)

[4. 6.]
