## Sorting Numpy Arrays

### Sorting Numeric Arrays

In [1]:
import numpy as np

print("unsorted array")
my_array = np.random.randint(1, 20, 10)
print(my_array)

print("\n sorted array")
sorted_array = np.sort(my_array)
print(sorted_array)

unsorted array
[ 3  3 19  4 10 11  9  1  6  8]

 sorted array
[ 1  3  3  4  6  8  9 10 11 19]


### Sorting Text Arrays

In [2]:
import numpy as np

print ("unsorted array")
my_array = np.array(["Red", "Green", "Blue", "Yello"])
print (my_array)

print (" \n sorted array")
sorted_array = np.sort(my_array)
print (sorted_array)

unsorted array
['Red' 'Green' 'Blue' 'Yello']
 
 sorted array
['Blue' 'Green' 'Red' 'Yello']


### Sorting Boolean Arrays

In [3]:
import numpy as np

print ("unsorted array")
my_array = np.array([False , True , True , False , False , True , False , True ])
print (my_array)

print (" \n Sorted array")
sorted_array = np.sort(my_array)
print (sorted_array)

unsorted array
[False  True  True False False  True False  True]
 
 Sorted array
[False False False False  True  True  True  True]


### Sorting 2-D Arrays

In [5]:
import numpy as np

print ("unsorted array")
my_array = np.random.randint( 1 , 20 , size = ( 4 , 6 ))
print (my_array)

print ("\nSorted array")
sorted_array = np.sort(my_array)
print (sorted_array)

unsorted array
[[11 16  2  2  2 10]
 [ 5 15 13  6  9  2]
 [15 19 10 14  6  9]
 [16  2  3  7 12  2]]

Sorted array
[[ 2  2  2 10 11 16]
 [ 2  5  6  9 13 15]
 [ 6  9 10 14 15 19]
 [ 2  2  3  7 12 16]]


### Sorting in Descending Order

In [6]:
import numpy as np

print ("unsorted array")
my_array = np.random.randint( 1 , 20 , 10 )
print (my_array)

print (" \n sorted array")
sorted_array = np.sort(my_array)
reverse_sorted = np.flipud(sorted_array)
print (reverse_sorted)

unsorted array
[ 9  5 11 14 18 19  6  6  8 10]
 
 sorted array
[19 18 14 11 10  9  8  6  6  5]


## Reshaping NumPy Arrays

### Reshaping from Lower to Higher Dimensions

In [7]:
import numpy as np

print ("one-dimensional array")
one_d_array = np.random.randint( 1 , 20 , 10 )
print (one_d_array)

print (" \n two-dimensional array")
two_d_array = one_d_array.reshape( 2 , 5 )
print (two_d_array)

one-dimensional array
[13 19 10  6  1  5 13 17  2 18]
 
 two-dimensional array
[[13 19 10  6  1]
 [ 5 13 17  2 18]]


In [8]:
import numpy as np

print ("one-dimensional array")
one_d_array = np.random.randint( 1 , 20 , 10 )
print (one_d_array)

print (" \n two-dimensional array")
two_d_array = np.reshape(one_d_array,( 2 , 5 ))
print (two_d_array)

one-dimensional array
[11  9  6  4 11 18  7 12 18  1]
 
 two-dimensional array
[[11  9  6  4 11]
 [18  7 12 18  1]]


In [10]:
import numpy as np

print ("two-dimensional array")
two_d_array = np.random.randint( 1 , 20 , size = ( 4 , 6 ))
print (two_d_array)

print (" \n three-dimensional array")
three_d_array = np.reshape(two_d_array,( 3 , 4 , 2 ))
print (three_d_array)

two-dimensional array
[[16 19  8 17 19  1]
 [15  4  4 16  5  3]
 [14 11  9 11  6 18]
 [16 10 15  8 12 15]]
 
 three-dimensional array
[[[16 19]
  [ 8 17]
  [19  1]
  [15  4]]

 [[ 4 16]
  [ 5  3]
  [14 11]
  [ 9 11]]

 [[ 6 18]
  [16 10]
  [15  8]
  [12 15]]]


### Reshaping from Higher to Lower Dimensions

In [11]:
import numpy as np

print ("two-dimensional array")
two_d_array = np.random.randint( 1 , 20 , size = ( 4 , 6 ))
print (two_d_array)

print (" \n one-dimensional array")
one_d_array = two_d_array.reshape( 24 )
print (one_d_array)

two-dimensional array
[[10 12 17  3  1  2]
 [ 1  6  8 15 19  1]
 [12 19 16 18 12  4]
 [16  7  1 16  2  6]]
 
 one-dimensional array
[10 12 17  3  1  2  1  6  8 15 19  1 12 19 16 18 12  4 16  7  1 16  2  6]


In [12]:
import numpy as np

print ("two-dimensional array")
two_d_array = np.random.randint( 1 , 20 , size = ( 4 , 6 ))
print (two_d_array)

print (" \n one-dimensional array")
one_d_array = two_d_array.reshape(- 1 )
print (one_d_array)

two-dimensional array
[[14  7 17  3  9 16]
 [17  1 15  4 17  5]
 [ 5 12 12 18  2  6]
 [ 3 17 12 16 10  6]]
 
 one-dimensional array
[14  7 17  3  9 16 17  1 15  4 17  5  5 12 12 18  2  6  3 17 12 16 10  6]


In [13]:
import numpy as np

print ("two-dimensional array")
three_d_array = np.random.randint( 1 , 20 , size = ( 4 , 2 , 6 ))
print (three_d_array)

print (" \n on-dimensional array")
one_d_array = three_d_array .reshape(- 1 )
print (one_d_array)

two-dimensional array
[[[ 4  7 16  1  4 19]
  [15 17  5 14 16 16]]

 [[10 10  6  4 16 10]
  [11 12  2 19 10 17]]

 [[14 10 17  5 10 11]
  [ 8 10 18  6 11  7]]

 [[ 6  4  2  1 17  9]
  [18 10  9 10 16  5]]]
 
 on-dimensional array
[ 4  7 16  1  4 19 15 17  5 14 16 16 10 10  6  4 16 10 11 12  2 19 10 17
 14 10 17  5 10 11  8 10 18  6 11  7  6  4  2  1 17  9 18 10  9 10 16  5]


## Indexing and Slicing NumPy Arrays

In [14]:
import numpy as np
s = np.arange( 1 , 11 )
print (s)

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
print (s[ 1 ])


2


In [16]:
print (s[ 1 : 9 ])

[2 3 4 5 6 7 8 9]


In [17]:
print (s[: 5 ])
print (s[ 5 :])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [18]:
row1 = [ 10 , 12 , 13 ]
row2 = [ 45 , 32 , 16 ]
row3 = [ 45 , 32 , 16 ]
nums_2d = np.array([row1, row2, row3])
print (nums_2d[: 2 ,:])

[[10 12 13]
 [45 32 16]]


In [19]:
row1 = [ 10 , 12 , 13 ]
row2 = [ 45 , 32 , 16 ]
row3 = [ 45 , 32 , 16 ]
nums_2d = np.array([row1, row2, row3])
print (nums_2d[:,: 2 ])

[[10 12]
 [45 32]
 [45 32]]


In [20]:
row1 = [ 10 , 12 , 13 ]
row2 = [ 45 , 32 , 16 ]
row3 = [ 45 , 32 , 16 ]
nums_2d = np.array([row1, row2, row3])
print (nums_2d[ 1 :, 1 :])

[[32 16]
 [32 16]]


## Broadcasting NumPy Arrays

In [21]:
import numpy as np
array1 = np.array ([ 14 , 25 , 31 ])
array2 = np.array([ 10 ])
result = array1 + array2
print (result)

[24 35 41]


In [23]:
array1 = np.random.randint( 1 , 20 , size = ( 3 , 4 ))
print (array1)
array2 = np.array([ 10 ])
print ("after brodcasting")
result = array1 + array2
print (result)

[[12 18 11 15]
 [12 18  7 12]
 [ 6  4 16 11]]
after broadcasting
[[22 28 21 25]
 [22 28 17 22]
 [16 14 26 21]]


In [24]:
array1 = np.random.randint( 1 , 20 , size = ( 3 , 4 ))
print (array1)
array2 = np.array([ 5 , 10 , 20 , 25 ])
print ("after bradcasting")
result = array1 + array2
print (result)

[[ 6  6  3 11]
 [12 14 11  5]
 [13  8 10  6]]
after bradcasting
[[11 16 23 36]
 [17 24 31 30]
 [18 18 30 31]]


In [25]:
array1 = np.random.randint( 1 , 20 , size = ( 3 , 4 ))
print (array1)
array2 = np.array([[ 5 ],[ 10 ],[ 20 ]])
print ("after bradcasting")
result = array1 + array2
print (result)

[[10 10 14 18]
 [15  5 14 10]
 [ 8  9 18 10]]
after bradcasting
[[15 15 19 23]
 [25 15 24 20]
 [28 29 38 30]]


## Copying NumPy Arrays

In [26]:
import numpy as np
array1 = np.array([ 10 , 12 , 14 , 16 , 18 , 20 ])
array2 = array1.copy()
array2[ 1 ] = 20
print (array1)
print (array2)

[10 12 14 16 18 20]
[10 20 14 16 18 20]


In [27]:
array1 = np.array([ 10 , 12 , 14 , 16 , 18 , 20 ])
array2 = array1.view()
array2[ 1 ] = 20
print (array1)
print (array2)

[10 20 14 16 18 20]
[10 20 14 16 18 20]


## NumPy I/O Operations

### Saving a NumPy Array

In [35]:
import numpy as np
array1 = np.array([ 10 , 12 , 14 , 16 , 18 , 20 ])
np.save(r"C:\Users\DILANE KAMGA\Documents\Dilane Kamga\COURSES\DATA SCIENCE\numpy\Python_NumPy_for_Beginners_NumPy_Specialization_for_Data_Scineces Codes\my_array",array1)

In [49]:
import numpy as np
array1 = np.array([ 10 , 12 , 14 , 16 , 18 , 20 ])
np.savetxt(r"C:\Users\DILANE KAMGA\Documents\Dilane Kamga\COURSES\DATA SCIENCE\numpy\Python_NumPy_for_Beginners_NumPy_Specialization_for_Data_Scineces Codes\my_array.txt",array1)

### Loading a NumPy Array

In [42]:
import numpy as np
loaded_array = np.load(r"C:\Users\DILANE KAMGA\Documents\Dilane Kamga\COURSES\DATA SCIENCE\numpy\Python_NumPy_for_Beginners_NumPy_Specialization_for_Data_Scineces Codes\my_array.npy")
print (loaded_array)

[10 12 14 16 18 20]


In [50]:
import numpy as np
loaded_array = np.loadtxt(r"C:\Users\DILANE KAMGA\Documents\Dilane Kamga\COURSES\DATA SCIENCE\numpy\Python_NumPy_for_Beginners_NumPy_Specialization_for_Data_Scineces Codes\my_array.txt")
print (loaded_array)

[10. 12. 14. 16. 18. 20.]
